# Generated by Django 4.2.5 on 2023-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
